pygments: true
permalink: /:year/:month/:day/:title
title: My Project Timeline
baseurl: /project-timeline
linked_posts: true

# Sets the default folder in Prose.io
# Sets the default metadata in Prose.io
prose:
  rooturl: "_posts"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
